image: python:3.12

stages:
  - test
  - build

test-stage:
  stage: test
  script:
    - apt-get update
    - apt-get install git-lfs
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
    - cd ..
    - python -m venv testing
    - source testing/bin/activate
    - cd CADET-RDM
    - pip install -U pytest setuptools
    - pip install .[testing]
    - pip list
    - ls -l
    - pytest tests -m "not server_api"

build-release:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+.*/
  stage: build
  script:
    - pip install -U build twine
    - python -m build
    - python -m twine upload dist/*
