-   id: rdm-check
    name: Update CADET-RDM remote links
    description: Update the links to the output repository in README.md and .cadet-rdm-data.json and stage them.
    entry: rdm check --no-commit --project-only --warn-only
    language: python
    pass_filenames: false
    always_run: true
    verbose: true
